name: release
on:
  push:
    branches: [ 'main' ]
    paths: [ '**', '!**.md' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
      - name: 'Release and push git tag'
        run: "git tag $(jq -r '.version' package.json) && git push --tags"
      - name: 'Create a GitHub release'
        run: "gh release create $(jq -r '.version' package.json) --generate-notes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
